const MESSAGING = {
 
  CHANGE_STATUS: 'CHANGE_STATUS',
  ADD_PROFILES: 'ADD_PROFILES',
  UPDATE_A_PROFILE: 'UPDATE_A_PROFILE',
  GET_ALL_DATA: 'GET_ALL_DATA',
  GET_PAGE_URL_CONTENT: 'GET_PAGE_URL_CONTENT',
  FETCH_REFRESH_DATA: 'FETCH_REFRESH_DATA',
  START_PARTIAL_PROFILES_DATA_COLLECTION: 'START_PARTIAL_PROFILES_DATA_COLLECTION',
  START_COMPLETE_PROFILES_DATA_COLLECTION: 'START_COMPLETE_PROFILES_DATA_COLLECTION',
  COLLECT_A_PROFILE_DATA: 'COLLECT_A_PROFILE_DATA',
  COLLECT_EMAILS_FROM_COMPANY_DATA: 'COLLECT_EMAILS_FROM_COMPANY_DATA',
}

const SCRAPING_STATUS = {
  IDLE: 'IDLE',
  COLLECTING_PROFILES_PARTIAL_DATA: 'COLLECTING_PROFILES_PARTIAL_DATA',
  COLLECTING_PROFILES_COMPLETE_DATA: 'COLLECTING_PROFILES_COMPLETE_DATA',
  READY_FOR_DOWNLOAD: 'READY_FOR_DOWNLOAD',
}

const FIREBASE_INIT = {
  apiKey: 'AIzaSyA9N_8DZNynJg7k9GhMzsDJPzPgFkByRgc',
  authDomain: 'linkedin-scrapper-38341.firebaseapp.com',
  projectId: 'linkedin-scrapper-38341',
  storageBucket: 'linkedin-scrapper-38341.appspot.com',
  messagingSenderId: '759247881103',
  appId: '1:759247881103:web:d524993bdfb1bc5c81c1fa',
  measurementId: 'G-K30RK7RRJ5',
}

export { MESSAGING, FIREBASE_INIT, SCRAPING_STATUS }
